//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avhrm.Tools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avhrm.Tools.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string APP_StringKeys_Account_Login {
            get {
                return ResourceManager.GetString("APP_StringKeys_Account_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string APP_StringKeys_Account_Password {
            get {
                return ResourceManager.GetString("APP_StringKeys_Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string APP_StringKeys_Account_Username {
            get {
                return ResourceManager.GetString("APP_StringKeys_Account_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن.
        /// </summary>
        public static string APP_StringKeys_Add {
            get {
                return ResourceManager.GetString("APP_StringKeys_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string APP_StringKeys_Delete {
            get {
                return ResourceManager.GetString("APP_StringKeys_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string APP_StringKeys_Description {
            get {
                return ResourceManager.GetString("APP_StringKeys_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string APP_StringKeys_Edit {
            get {
                return ResourceManager.GetString("APP_StringKeys_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انجام عملیات مشکلی بوجود آمده است.
        /// </summary>
        public static string APP_StringKeys_Error_Fail {
            get {
                return ResourceManager.GetString("APP_StringKeys_Error_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات کاربری یافت نشد.
        /// </summary>
        public static string APP_StringKeys_Error_Login {
            get {
                return ResourceManager.GetString("APP_StringKeys_Error_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرکردن فیلد &apos;{0}&apos; الزامی است.
        /// </summary>
        public static string APP_StringKeys_Error_Required {
            get {
                return ResourceManager.GetString("APP_StringKeys_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از تاریخ.
        /// </summary>
        public static string APP_StringKeys_FromDate {
            get {
                return ResourceManager.GetString("APP_StringKeys_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از ساعت.
        /// </summary>
        public static string APP_StringKeys_FromTime {
            get {
                return ResourceManager.GetString("APP_StringKeys_FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string APP_StringKeys_Id {
            get {
                return ResourceManager.GetString("APP_StringKeys_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بارگذاری...
        /// </summary>
        public static string APP_StringKeys_Loading {
            get {
                return ResourceManager.GetString("APP_StringKeys_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد.
        /// </summary>
        public static string APP_StringKeys_Message_Success {
            get {
                return ResourceManager.GetString("APP_StringKeys_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخص نشده.
        /// </summary>
        public static string APP_StringKeys_NotSpecified {
            get {
                return ResourceManager.GetString("APP_StringKeys_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string APP_StringKeys_SaveDate {
            get {
                return ResourceManager.GetString("APP_StringKeys_SaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا تاریخ.
        /// </summary>
        public static string APP_StringKeys_ToDate {
            get {
                return ResourceManager.GetString("APP_StringKeys_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا ساعت.
        /// </summary>
        public static string APP_StringKeys_ToTime {
            get {
                return ResourceManager.GetString("APP_StringKeys_ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت مرخصی.
        /// </summary>
        public static string APP_StringKeys_VacReq_Index {
            get {
                return ResourceManager.GetString("APP_StringKeys_VacReq_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تائید.
        /// </summary>
        public static string APP_StringKeys_VacReq_IsVerified {
            get {
                return ResourceManager.GetString("APP_StringKeys_VacReq_IsVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد شده.
        /// </summary>
        public static string APP_StringKeys_VacReq_NotVerified {
            get {
                return ResourceManager.GetString("APP_StringKeys_VacReq_NotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید شده.
        /// </summary>
        public static string APP_StringKeys_VacReq_Verified {
            get {
                return ResourceManager.GetString("APP_StringKeys_VacReq_Verified", resourceCulture);
            }
        }
    }
}
